// <auto-generated />
namespace Vidly.Wep.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GenreRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202101311106466_GenreRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
