// <auto-generated />
namespace Vidly.Wep.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpMovies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpMovies));
        
        string IMigrationMetadata.Id
        {
            get { return "202101261002302_UpMovies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
